# Application Name
spring.application.name=spring-learn

# Server Port
server.port=8080

# Logging Level
logging.level.root=INFO

# Console Log Pattern (Optional)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
