-- ============================================================
-- Scenario 2 : Maintain Transaction Audit Log
-- ============================================================

CREATE TABLE Transactions(

    TransactionID NUMBER PRIMARY KEY,
    AccountID NUMBER,
    Amount NUMBER,
    TransactionType VARCHAR2(20)

);

CREATE TABLE AuditLog(

    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    ActionDate DATE,
    ActionPerformed VARCHAR2(50)

);

CREATE OR REPLACE TRIGGER LogTransaction

AFTER INSERT
ON Transactions

FOR EACH ROW

BEGIN

    INSERT INTO AuditLog
    (
        TransactionID,
        ActionDate,
        ActionPerformed
    )

    VALUES
    (
        :NEW.TransactionID,
        SYSDATE,
        'INSERT'
    );

END;
/

INSERT INTO Transactions
VALUES(101,1,5000,'Deposit');

COMMIT;

SELECT * FROM AuditLog;